yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField('описание группы', max_length=400)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    posts = Post.objects.order_by('-pub_date')
    group = models.ForeignKey(
        Group,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

POSTS_PER_PAGE = 10


def index(request):
    posts = Post.posts[:POSTS_PER_PAGE]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts[:POSTS_PER_PAGE]
    context = {
        'group': group,
        'posts': posts,
    }
    print(posts)
    return render(request, 'posts/group_list.html', context)

templates/posts/index.html
<!-- templates/posts/index.html -->
<!DOCTYPE html>
<html lang="ru">
  <head>
  </head>
  <body>
    <h1>Главная страница</h1>
  </body>
</html>

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{% block title%}{% endblock %}</title>
</head>
<body>
<header>
    {% include 'includes/header.html' %}
</header>
{% block content %}
{% endblock %}
<footer>
    {% include 'includes/footer.html' %}
</footer>
</body>
</html>

yatube/templates/includes/footer.html
 <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>

yatube/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
    <head> {% load static %} ></head>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">

          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>

yatube/templates/posts/group_list.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Записи сообщества {{ group }}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <h1>{{ group }}</h1>
        <p></p>
          {% for post in posts %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{title}}
{% endblock %}
{% block content %}
      </div>
        <h1>Последние обновления на сайте</h1>
        <article>
            {% for post in posts %}
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              <p>{{ post.text }}</p>
            {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                  {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}

        </article>
       <!-- под последним постом нет линии -->
      </div>
{% endblock %}  